name: Publish

on:
  # Trigger the deploy on push to main branch
  push:
    branches:
      - main

jobs: 
  # This job deploys the example book
  deploy-example-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    # Install Requirements
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install jupyter-book
        pip install ghp-import
    # Build the example book
    - name: Build book
      run: |
        jupyter-book build .
    # Deploy html to gh-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: _build/html
        publish_branch: gh-pages
